# Generated by Django 4.1 on 2024-04-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
