# Generated by Django 4.1 on 2024-04-06 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewa', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='managers',
            field=models.ManyToManyField(related_name='managed_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='_store_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
