# Generated by Django 4.1 on 2024-04-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewa', '0007_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_store_name',
        ),
    ]
